---
- hosts: all
  gather_facts: no

  tasks:
    - name: Shell - hello
      shell: echo hello
      register: greeting

    - name: Debug - greeting
      debug:
        msg: "{{ greeting.stdout }}"
